### ISSUE TITLE
Option/shortcut to tint the interior of the window white

### ISSUE THREAD

**Issue by djdmbrwsk** [atdrago/negative#105]
When trying to grab a screenshot of a dark design mocked up within an iPhone frame, it was hard to see if the edges of the Negative window were aligned with the edge of the design. It may be helpful to allow users to tint the interior of the window white or remove the tint all together.

**Comment by atdrago** [comment]
Great idea!

It might make sense to also change window "frame" color too. Something like Light/Dark mode.

This should be added to "View > Dark Mode", as a checkbox menu item, defaulted to checked. Below "Clear" and above "Actual Size", with separators on either side.

**Comment by atdrago** [comment]
Just a sample. Thoughts?

**Dark Mode**
![dark-mode-start](https://cloud.githubusercontent.com/assets/144225/15562191/01c5536a-22b2-11e6-93c6-52dde6ae4c2e.png)
![dark-mode-capture](https://cloud.githubusercontent.com/assets/144225/15562189/01bc68ae-22b2-11e6-9c9e-caa2471a089b.png)

**Light Mode**
![light-mode-start](https://cloud.githubusercontent.com/assets/144225/15562188/018d0046-22b2-11e6-99da-1d01a76fa2ec.png)
![light-mode-capture](https://cloud.githubusercontent.com/assets/144225/15562190/01bdcdb6-22b2-11e6-9a4c-74e5af70787f.png)

**Comment by djdmbrwsk** [comment]
Looks great!
